nav:
  - name: Home
    path: /
  - name: About
    path: /about
  - name: Services
    path: /services
  - name: Blog
    path: /blog
  - name: Contact
    path: /contact

post_types:
  - name: Case Study
  - name: Technology
