# nav:
  # - name: Home
  #   path: /
  # - name: About
  #   path: /about
  # - name: Services
  #   path: /services
  # - name: Blog
  #   path: /blog

post_types:
  - name: Case Study
  - name: Technology

external_links:
  - name: LinkedIn
    url: https://www.linkedin.com/company/ratiopbc/
  - name: GitHub
    url: https://github.com/RatioPBC
  - name: Bluesky
    url: https://bsky.app/profile/ratiopbc.com

email: hello@ratiopbc.com
